import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Toaster } from 'react-hot-toast';

const geistSans = localFont({
  src: '../styles/fonts/Geist[wght].woff2',
  variable: '--font-geist-sans',
  display: 'swap',
  fallback: ['system-ui', 'arial'],
});

const geistMono = localFont({
  src: '../styles/fonts/GeistMono[wght].woff2',
  variable: '--font-geist-mono',
  display: 'swap',
  fallback: [
    'ui-monospace',
    'SFMono-Regular',
    'Menlo',
    'Monaco',
    'Consolas',
    'Liberation Mono',
    'Courier New',
    'monospace',
  ],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Toaster
          position="top-center"
          toastOptions={{
            style: {
              background: '#333',
              color: '#fff',
            },
          }}
        />
        {children}
        <div id="modal-root"></div>
      </body>
    </html>
  );
}
